default_language_version:
  python: python3.10

repos:
  - repo: local

    hooks:
      - id: bandit
        name: Bandit
        entry: poetry run bandit
        language: system
        types: [ python ]
        args: [ '--config', 'config/bandit.yml', '--severity-level', 'medium' ]

      - id: black
        name: Black
        entry: poetry run black
        language: system
        types: [ python ]
        args: [ "--line-length", "120" ]

      - id: flake8
        name: Flake8
        entry: poetry run flake8
        language: system
        types: [ python ]
        args: [ '--config=config/.flake8' ]

      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [ python ]
        args: [ '--settings-path=config/.isort.cfg' ]

      - id: mypy
        name: Mypy
        entry: poetry run mypy
        language: system
        types: [ python ]
        args: [ '--config-file', 'config/mypy.ini' ]

#      - id: pydocstyle
#        name: Pydocstyle
#        entry: poetry run pydocstyle
#        language: system
#        types: [ python ]
#        args: [ '--config=config/.pydocstyle' ]

      #      - id: pylint
      #        name: Pylint
      #        entry: poetry run pylint
      #        language: system
      #        types: [python]
      #        args: ['--rcfile=config/.pylintrc']

#      # Note: The confcutdir argument doesn't appear to work, requiring the tests directory to be specified here
#      - id: pytest
#        name: Pytest
#        entry: poetry run pytest
#        language: system
#        types: [ python ]
#        args: [ "--confcutdir=config", "tests" ]
